version: '3.3'

services:
  bd:
    image: mysql:5.7
    restart: "always"
    container_name: mysql-zabbix
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=Zabbix
    volumes:
      - /var/docker/zabbix/data:/var/lib/data
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']
    networks:
      testing_net:
        ipv4_address: 172.28.0.2

  zabbix:
    image: zabbix/zabbix-server-mysql:ubuntu-4.4.7
    restart: "always"
    container_name: zabbix-server
    ports:
      - "10050:10050"
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=172.28.0.2
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
    volumes:
      - /var/docker/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /var/docker/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
    depends_on:
      - bd
    networks:
      testing_net:
        ipv4_address: 172.28.0.3
  
  webserver:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-4.4.7
    restart: "always"
    container_name: zabbix-web
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DB_SERVER_HOST=172.28.0.2
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - ZBX_SERVER_HOST=172.28.0.3
      - PHP_TZ='America/Sao_Paulo'
    depends_on:
      - bd
      - zabbix
    networks:
      testing_net:
        ipv4_address: 172.28.0.4

     grafana:
    image: grafana/grafana:master-ubuntu
    restart: "always"
    container_name: grafana
    ports:
      - "3000:3000"
    #volumes:
    #  - /var/docker/grafana:/var/lib/grafana
    #  - /var/docker/grafana/plugins:/var/lib/grafana/plugins
    command: ['bash', 'grafana-cli plugins install alexanderzobnin-zabbix-app']
    depends_on:
      - bd
      - zabbix
      - webserver
    networks:
      testing_net:
        ipv4_address: 172.28.0.5

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
